### ISSUE TITLE
Empty Recs Template Defaults

### ISSUE THREAD

**Issue by korgon** [searchspring/snapfu#18]
Currently templates do not support empty default parameters, but they should:

```
{
	"parameters": [
		{
			"name": "headerText",
			"label": "Header Text",
			"description": "the header text of this custom template",
			"defaultValue": ""
		}
	]
}
```

Currently when syncing a template, the operation fails with an unknown error (also not helpful).

**Comment by chrisFrazier77** [comment]
https://github.com/searchspring/smc-config-api/pull/60
