### ISSUE TITLE
More Snap Templates

### ISSUE THREAD

**Issue by njkuhne** [searchspring/snapfu#28]
- [ ] fully built custom components with sass
- [ ] content tabs
- [ ] refine boilerplate
- [ ] use Springboard skeleton as example of a good starting point, add "key" attribute
- [ ] sass style blocks for quick starting
- [ ] autocomplete component template
- [ ] component theming

**Comment by njkuhne** [comment]
@korgon we may want to break this task down, given all of the todo items in here. Your choice :)

**Comment by julesbravo** [comment]
@njkuhne Can we get @adriamurphy involved in the shaping of this work? Her input on this is going to be greatly valuable for this.

**Comment by korgon** [comment]
Additional templates are being built by and have been built by the implementations team. We will be adding support for using these in Snapfu in the near future.
