### ISSUE TITLE
Move templates out of snapfu

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snapfu#38]
Seems like we may want to move these out into some other location some day so that it doesn't take a full `snapfu` release to update...

_Originally posted by @korgon in https://github.com/searchspring/snapfu/pull/37#pullrequestreview-944848336_

**Comment by korgon** [comment]
Perhaps we could utilize a repository of component templates?

Eg: https://github.com/searchspring/snapfu-template-preact-components

**Comment by korgon** [comment]
Merged into `develop`.

**Comment by korgon** [comment]
Released in v1.5.0
