### ISSUE TITLE
Support Init on `User` Organization

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snapfu#51]
If the logged in user does not have any permission to create repos in any of the organizations, you get an error being thrown when inquirer prompts the organization question. Let's check if any orgs are present before prompting the questions and log a message. 

See image: https://searchspring.slack.com/archives/CRQDMSWBT/p1657634174867949

**Comment by korgon** [comment]
Should we allow creating repo in user space (non-organization) ?

**Comment by korgon** [comment]
Added support for non-organization usage in v1.0.23.
