### ISSUE TITLE
Recommendations Archive

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snapfu#88]
Running ```snapfu recs archive``` requires you to have the branch created locally in order to archive a branched template. From previous discussion with @korgon you should be able to archive without the local branch being present.
https://capture.dropbox.com/cUoi8HOIWnbkkjBR

**Comment by korgon** [comment]
@adriamurphy Are you saying the `snapfu recs archive` command is not working when passing it a branch?

<img width="824" alt="image" src="https://github.com/searchspring/snap/assets/5060400/1a71682d-c7c0-401d-abf7-75bd9bb0bc11">

**Comment by korgon** [comment]
@adriamurphy Have you tried `snapfu recs archive <name> <branch>`? As that should work wether or not you have the branch pulled or checked out.

**Comment by adriamurphy** [comment]
@korgon Sorry I never see these notices. 

In my screenshot, I tried to archive a recs template with `snapfu recs archive carousel adria/initial` using branch and template name. However, it would not archive because I didn't have that branch locally. It existed on the repo, but not on my machine. I could only archive this template when creating the branch locally again.
